/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Conexion.conexion;
import Formulario.Inicio;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author edin1
 */
public class Usuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuairos
     */
    public Usuarios() {
        initComponents();
        CargarTabla();
    }
    static conexion cc = new conexion();
    static Connection cn = cc.Conectar();
   static public int bandera,usuario_id;

   static public void CargarTabla() {
        Tabla.setModel(Controlador.tablausuario(cn));
    }
   Controlador control=new Controlador();
void Editar() {
        int fila = Usuarios.Tabla.getSelectedRow();
        if (fila < -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una Fila");
        } else {
            ArrayList<Modelo> Datos = control.obtener(cn,Tabla.getValueAt(fila, 1).toString());
            if (Datos.size() == 0) {
                JOptionPane.showMessageDialog(null, "Usuario No Encontrado");
            } else {
        usuario_id=Datos.get(0).getUsuario_id();
        Guardar_Editar_Borrar.jtflContra.setText(Datos.get(0).getContrasenia());
        Guardar_Editar_Borrar.jtflCorreo.setText(Datos.get(0).getCorreo_electronico());
        Guardar_Editar_Borrar.jtflDireccion.setText(Datos.get(0).getDireccion());
        Guardar_Editar_Borrar.jtflFechaNacimiento.setDate(Datos.get(0).getFecha_nacimiento());//parentesis de mas
        Guardar_Editar_Borrar.jtflTelefono.setText(String.valueOf(Datos.get(0).getTelefono()));
        Guardar_Editar_Borrar.jtflapellido.setText(Datos.get(0).getApellido());
        Guardar_Editar_Borrar.jtflnombre.setText(Datos.get(0).getNombre());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jButton1.setText("Modificar Usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar  Usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblUsuario.setText("Usuario:Nombre Apellido");

        jMenu1.setText("Agregar usuario");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Guardar_Editar_Borrar guardar = new Guardar_Editar_Borrar();
        Inicio.Escritorio.add(guardar);
        guardar.setVisible(true);
        bandera = 0;
        guardar.btnOk.setText("Guardar");
        guardar.lblNombre.setText("Agregar Usuario");
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Inicio.activarlogin = true;
        this.setVisible(false);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Guardar_Editar_Borrar editar = new Guardar_Editar_Borrar();
        Inicio.Escritorio.add(editar);
        editar.setVisible(true);
        bandera = 1;
        Editar();
        editar.btnOk.setText("Guardar Cambiaos");
        editar.lblNombre.setText("Modificar Usuario");
        Guardar_Editar_Borrar.jradioActivo.setVisible(false);
        Guardar_Editar_Borrar.jradioInactivo.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Guardar_Editar_Borrar borrar = new Guardar_Editar_Borrar();
        Inicio.Escritorio.add(borrar);
        borrar.setVisible(true);
        Editar();
        bandera = 2;
        borrar.btnOk.setText("Eliminar Usuario");
        borrar.lblNombre.setText("Eleminar Usuario");  
        Guardar_Editar_Borrar.jtflContra.setEnabled(false);
        Guardar_Editar_Borrar.jtflCorreo.setEnabled(false);
        Guardar_Editar_Borrar.jtflDireccion.setEnabled(false);
        Guardar_Editar_Borrar.jtflFechaNacimiento.setEnabled(false);
        Guardar_Editar_Borrar.jtflTelefono.setEnabled(false);
        Guardar_Editar_Borrar.jtflapellido.setEnabled(false);
        Guardar_Editar_Borrar.jtflnombre.setEnabled(false);
        Guardar_Editar_Borrar.jradioActivo.setVisible(false);
        Guardar_Editar_Borrar.jradioInactivo.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
